/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leituradelog;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class FormPrincipal extends javax.swing.JFrame {
    List<Dados> listaDados = new ArrayList<>();
    JFrame frame = new JFrame("Título");

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        seuTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leitor de Log");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Ler e Mostrar Dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea2.setDragEnabled(true);
        jScrollPane1.setViewportView(jTextArea2);

        jButton3.setText("Calculos de IP");
        jButton3.setPreferredSize(new java.awt.Dimension(113, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Calculos de Horas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Calculos de Navegadores");
        jButton5.setPreferredSize(new java.awt.Dimension(113, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seuTextField.setText("Caminho do Arquivo TXT");

        jButton2.setText("Abrir Arquivo TXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seuTextField)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Media:");

        jLabel2.setText(" ");

        jLabel3.setText("Moda:");

        jLabel4.setText(" ");

        jLabel5.setText("Mediana:");

        jLabel6.setText(" ");

        jLabel7.setText("Variância:");

        jLabel8.setText(" ");

        jLabel9.setText("Desvio Padrao:");

        jLabel10.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton6.setText("Gerar Grafico de Navegadores");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Gerar Grafico de Horas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listaDados = ManipulaArquivo.lerDados(seuTextField.getText());
        for (Dados dados : listaDados){
            jTextArea2.append(dados.toString()+"\n");
            
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser arquivo = new JFileChooser();
            FileNameExtensionFilter filtroTXT = new FileNameExtensionFilter("Arquivos TXT", "txt");  
            arquivo.addChoosableFileFilter(filtroTXT);
            arquivo.setAcceptAllFileFilterUsed(false);
            if(arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            seuTextField.setText(arquivo.getSelectedFile().getAbsolutePath());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jLabel2.setText(CalculosIp.mediaIP(listaDados)+"");
       jLabel4.setText(CalculosIp.modaIp(listaDados));
       jLabel6.setText(CalculosIp.medianaIP(listaDados)+"");
       jLabel8.setText(CalculosIp.varIP(listaDados)+"");
       jLabel10.setText(CalculosIp.dpIP(listaDados)+"");
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    jTextArea2.setText("");
    jTextArea2.setText("Navegadores|      ni      |                  100.fi                  "+"\n");
    jTextArea2.append("Mozilla            |"+CalculosNavegador.mozilaNav(listaDados)+"             |"+100*(CalculosNavegador.mozilaNav(listaDados)/CalculosNavegador.ttNav(listaDados))+"\n");
    jTextArea2.append("Chrome         |"+CalculosNavegador.chromeNav(listaDados)+"             |"+100*(CalculosNavegador.chromeNav(listaDados)/CalculosNavegador.ttNav(listaDados))+"\n");
    jTextArea2.append("Edge              |"+CalculosNavegador.edgeNav(listaDados)+"             |"+100*(CalculosNavegador.edgeNav(listaDados)/CalculosNavegador.ttNav(listaDados))+"\n");
    jTextArea2.append("Opera            |"+CalculosNavegador.operaNav(listaDados)+"             |"+100*(CalculosNavegador.operaNav(listaDados)/CalculosNavegador.ttNav(listaDados))+"\n");
    jTextArea2.append("Safari             |"+CalculosNavegador.safariNav(listaDados)+"             |"+100*(CalculosNavegador.safariNav(listaDados)/CalculosNavegador.ttNav(listaDados))+"\n");
        


    // TODO add your handling code here:
        jLabel2.setText("");
        jLabel4.setText(CalculosNavegador.modaNav(listaDados));
        jLabel6.setText("");
        jLabel8.setText("");
        jLabel10.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
    jTextArea2.setText("Classes de horas|      Si      |                  ni                  |                  Si.ni                  |                  100.fi                  "+"\n");
    jTextArea2.append(" 0 - 1                        |0.5       |"+CalculosHora.zeroum(listaDados)+"                                      |"+ CalculosHora.zeroum(listaDados)*0.5 + "                                      |"+ 100*(CalculosHora.zeroum(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 1 - 2                        |1.5       |"+CalculosHora.umdois(listaDados)+"                                      |"+ CalculosHora.umdois(listaDados)*1.5 + "                                      |"+ 100*(CalculosHora.umdois(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 2 - 3                        |2.5       |"+CalculosHora.doistres(listaDados)+"                                      |"+ CalculosHora.doistres(listaDados)*2.5 + "                                      |"+ 100*(CalculosHora.doistres(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 3 - 4                        |3.5       |"+CalculosHora.tresquatro(listaDados)+"                                      |"+ CalculosHora.tresquatro(listaDados)*3.5 + "                                    |"+ 100*(CalculosHora.tresquatro(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 4 - 5                        |4.5       |"+CalculosHora.quatrocinco(listaDados)+"                                      |"+ CalculosHora.quatrocinco(listaDados)*4.5 + "                                      |"+ 100*(CalculosHora.quatrocinco(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 5 - 6                        |5.5      |"+CalculosHora.cincoseis(listaDados)+"                                      |"+ CalculosHora.cincoseis(listaDados)*5.5 + "                                      |"+ 100*(CalculosHora.cincoseis(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 6 - 7                        |6.5       |"+CalculosHora.seissete(listaDados)+"                                      |"+ CalculosHora.seissete(listaDados)*6.5 + "                                      |"+ 100*(CalculosHora.seissete(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 7 - 8                        |7.5       |"+CalculosHora.seteoito(listaDados)+"                                      |"+ CalculosHora.seteoito(listaDados)*7.5 + "                                      |"+ 100*(CalculosHora.seteoito(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 8 - 9                        |8.5       |"+CalculosHora.oitonove(listaDados)+"                                      |"+ CalculosHora.oitonove(listaDados)*8.5 + "                                      |"+ 100*(CalculosHora.oitonove(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 9 - 10                       |9.5      |"+CalculosHora.novedez(listaDados)+"                                      |"+ CalculosHora.novedez(listaDados)*9.5 + "                                      |"+ 100*(CalculosHora.novedez(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
        
    jTextArea2.append(" 10 - 11                   |10.5      |"+CalculosHora.dezonze(listaDados)+"                                     |"+ CalculosHora.dezonze(listaDados)*10.5+ "                                      |"+ 100*(CalculosHora.dezonze(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 11 - 12                   |11.5      |"+CalculosHora.onzedoze(listaDados)+"                                     |"+ CalculosHora.onzedoze(listaDados)*11.5+ "                                      |"+ 100*(CalculosHora.onzedoze(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 12 - 13                   |12.5      |"+CalculosHora.dozetreze(listaDados)+"                                     |"+ CalculosHora.dozetreze(listaDados)*12.5+ "                                      |"+ 100*(CalculosHora.dozetreze(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 13 - 14                   |13.5      |"+CalculosHora.trezeca(listaDados)+"                                     |"+ CalculosHora.trezeca(listaDados)*13.5+ "                                      |"+ 100*(CalculosHora.trezeca(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 14 - 15                   |14.5     |"+CalculosHora.caqui(listaDados)+"                                     |"+ CalculosHora.caqui(listaDados)*14.5+ "                                      |"+ 100*(CalculosHora.caqui(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 15 - 16                   |15.5      |"+CalculosHora.quidezess(listaDados)+"                                     |"+ CalculosHora.quidezess(listaDados)*15.5+ "                                      |"+ 100*(CalculosHora.quidezess(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 16 - 17                   |16.5     |"+CalculosHora.dezzesdezsete(listaDados)+"                                     |"+ CalculosHora.dezzesdezsete(listaDados)*16.5+ "                                      |"+ 100*(CalculosHora.dezzesdezsete(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 17 - 18                   |17.5      |"+CalculosHora.dezsetdezoito(listaDados)+"                                     |"+ CalculosHora.dezsetdezoito(listaDados)*17.5+ "                                      |"+ 100*(CalculosHora.dezsetdezoito(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 18 - 19                   |18.5      |"+CalculosHora.dezoitonove(listaDados)+"                                     |"+ CalculosHora.dezoitonove(listaDados)*18.5+ "                                      |"+ 100*(CalculosHora.dezoitonove(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 19 - 20                   |19.5     |"+CalculosHora.deznovevinte(listaDados)+"                                     |"+ CalculosHora.deznovevinte(listaDados)*19.5+ "                                      |"+ 100*(CalculosHora.deznovevinte(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 20 - 21                   |20.5      |"+CalculosHora.vintevinteum(listaDados)+"                                     |"+ CalculosHora.vintevinteum(listaDados)*20.5+ "                                      |"+ 100*(CalculosHora.vintevinteum(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 21 - 22                   |21.5      |"+CalculosHora.vinteeumvintedois(listaDados)+"                                     |"+ CalculosHora.vinteeumvintedois(listaDados)*21.5+ "                                      |"+ 100*(CalculosHora.vinteeumvintedois(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 22 - 23                   |22.5      |"+CalculosHora.vinteedoisvintetres(listaDados)+"                                     |"+ CalculosHora.vinteedoisvintetres(listaDados)*22.5+ "                                      |"+ 100*(CalculosHora.vinteedoisvintetres(listaDados)/CalculosHora.ttHr(listaDados))+"\n");
    jTextArea2.append(" 23 - 00                   |23.5      |"+CalculosHora.vintetreszero(listaDados)+"                                     |"+ CalculosHora.vintetreszero(listaDados)*23.5+ "                                      |"+ 100*(CalculosHora.vintetreszero(listaDados)/CalculosHora.ttHr(listaDados))+"\n");




    jLabel4.setText(CalculosHora.moda(listaDados)+"");

       jLabel2.setText(CalculosHora.mediaHr(listaDados)+"");
       jLabel4.setText(CalculosHora.moda(listaDados));
       jLabel6.setText(CalculosHora.medianaHr(listaDados)+"");
       jLabel8.setText(CalculosHora.varHr(listaDados)+"");
       jLabel10.setText(CalculosHora.dpHr(listaDados)+"");        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Grafico.grafico(listaDados);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try {
            GraficoHora.grafico(listaDados);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField seuTextField;
    // End of variables declaration//GEN-END:variables
}
